(function(g){var window=this;var j4=function(a,b,c){var d=b.sa();g.I(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.yc(c?c:"mqdefault.jpg");var f=b instanceof g.rB&&b.lengthSeconds?g.dR(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.mE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.rB?b.va:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.jj||g.JN("Ver $TITLE",{TITLE:b.title}),duration:f,url:b.Uh(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.oE&&(d.playlist_length=b.getLength());a.update(d)},k4=function(a,b){g.lD.call(this,{B:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},l4=function(a){g.W.call(this,{B:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",V:"Siguiente"},{B:"span",G:"ytp-upnext-title",V:"{{title}}"},{B:"span",G:"ytp-upnext-author",V:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente v\u00eddeo"},J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},J:[{B:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",
V:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({B:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},V:"Cancelar"});g.B(this,this.A);this.A.da("click",this.qI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.J(this.Wl,5E3,this);g.B(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],
"click",this.dK);this.Iy();this.K(a,"autonavvisibility",this.Iy);this.K(a,"mdxnowautoplaying",this.vJ);this.K(a,"mdxautoplaycanceled",this.wJ);this.K(a,"mdxautoplayupnext",this.fB);3==this.l.getPresentingPlayerType()&&(a=(a=g.AK(g.uK(this.l)))?a.lD():null)&&this.fB(a)},m4=function(a,b){if(!a.o){g.jq("a11y-announce","Siguiente "+a.u.title);
a.H=g.M();a.o=new g.J((0,g.x)(a.ep,a,b),25);a.ep(b);var c=b||g.P(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.lo(a.element,"ytp-upnext-autoplay-paused")},o4=function(a){n4(a);
a.H=g.M();a.ep();g.H(a.element,"ytp-upnext-autoplay-paused")},n4=function(a){a.o&&(a.o.dispose(),a.o=null)},p4=function(a,b){b=void 0===b?!1:b;
if(g.O(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.sa(),a.Wl(),a.C=new Notification("Siguiente",{body:c.title,icon:c.yc()}),a.D=a.K(a.C,"click",a.VJ),a.F.start())}n4(a);a.l.nextVideo(!1,b)},q4=function(a){k4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Sd}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",V:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.B(this,this.l);this.l.g(this.element);this.o=new g.pW("Suscribirse",null,"Cancelar suscripci\u00f3n",null,!0,!1,b.Sf,b.subscribed,"trailer-endscreen",null,null,a);g.B(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},
r4=function(a){var b=g.X(a),c=g.jx||g.Dh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{B:"a",W:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",V:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",V:"En directo"},{B:"span",G:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{B:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Lista de reproducci\u00f3n",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",V:"{{playlist_length}}"},")"]}]},{B:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Ps(this);g.B(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.X(a).F&&g.xO(a.app.T,this.element,this);this.C()},s4=function(a){g.QK(a.l,a.element);
var b=a.o.sa().videoId,c=a.o.getPlaylistId();g.vY(a.l.app,b,a.o.Ub,c,void 0,void 0)},t4=function(a){k4.call(this,a,"videowall-endscreen");
this.F=a;this.A=0;this.o=[];this.C=this.O=this.u=null;this.D=this.P=!1;this.M=null;this.ca=new g.Ps(this);g.B(this,this.ca);this.H=new g.J(g.Qa(g.H,this.element,"ytp-show-tiles"),0);g.B(this,this.H);var b=new g.W({B:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Anterior"},J:[g.MP()]});g.B(this,b);b.g(this.element);b.da("click",this.HF,this);this.I=new g.gD({B:"div",G:"ytp-endscreen-content"});g.B(this,this.I);this.I.g(this.element);b=new g.W({B:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Siguiente"},J:[g.NP()]});g.B(this,b);b.g(this.element);b.da("click",this.GF,this);this.l=new l4(a);g.B(this,this.l);g.NK(this.player,this.l.element,4);this.hide()},u4=function(a){return g.OK(a.player)&&a.zu()&&!a.C},v4=function(a,b){return(0,g.ge)(b.suggestions,function(c){c=g.sS(g.X(a.F),c);
g.B(a,c);return c})},w4=function(a){var b=a.Pe();
b!=a.P&&(a.P=b,a.player.N("autonavvisibility"))},y4=function(a){g.aL.call(this,a);
this.g=null;this.i=new g.Ps(this);g.B(this,this.i);this.l=g.X(a);x4(a)?this.g=new t4(this.player):this.l.Ja?this.g=new q4(this.player):this.g=new k4(this.player);g.B(this,this.g);g.NK(this.player,this.g.element,4);this.bA();this.i.K(a,"videodatachange",this.bA,this);this.i.K(a,g.lE("endscreen"),this.VE,this);this.i.K(a,"crx_endscreen",this.WE,this)},x4=function(a){a=g.X(a);
return a.Fa&&!a.Ja};
g.t(k4,g.lD);k4.prototype.create=function(){this.created=!0};
k4.prototype.destroy=function(){this.created=!1};
k4.prototype.zu=function(){return!1};
k4.prototype.Pe=function(){return!1};g.t(l4,g.W);g.h=l4.prototype;g.h.Wl=function(){this.C&&(this.F.stop(),this.Ma(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.Iy=function(){g.kD(this,this.l.Pe())};
g.h.VJ=function(){window.focus();this.Wl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.ep=function(a){a=a||g.P(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.M()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?p4(this,!0):this.o&&this.o.start()};
g.h.dK=function(a){!g.$d(this.A.element,g.hs(a))&&g.vS(a,this.l)&&p4(this)};
g.h.qI=function(){g.wK(this.l,!0)};
g.h.vJ=function(a){this.l.getPresentingPlayerType();this.show();m4(this,a)};
g.h.fB=function(a){this.l.getPresentingPlayerType();this.u&&this.u.sa().videoId==a.sa().videoId||(this.u=a,j4(this,a,"hqdefault.jpg"))};
g.h.wJ=function(){this.l.getPresentingPlayerType();n4(this);this.hide()};
g.h.U=function(){n4(this);this.Wl();g.W.prototype.U.call(this)};g.t(q4,k4);g.t(r4,g.W);r4.prototype.D=function(a){g.vS(a,this.l,this.A,this.o.Ub||void 0)&&s4(this)};
r4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.ms(a)||(s4(this),g.ls(a))}};
r4.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Pb?!1:b.i};g.t(t4,k4);g.h=t4.prototype;g.h.create=function(){k4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=v4(this,a),this.O=a);this.Lf();this.ca.K(this.player,"appresize",this.Lf);this.ca.K(this.player,"onVideoAreaChange",this.Lf);this.ca.K(this.player,"videodatachange",this.IF);this.ca.K(this.player,"autonavchange",this.qr);this.ca.K(this.player,"autonavcancel",this.FF);a=this.O.autonavState;a!=this.M&&this.qr(a);this.ca.K(this.element,"transitionend",this.sL)};
g.h.destroy=function(){g.Rs(this.ca);g.sf(this.o);this.o=[];this.u=null;k4.prototype.destroy.call(this);g.lo(this.element,"ytp-show-tiles");this.H.stop();this.M=this.O.autonavState};
g.h.zu=function(){return 1!=this.O.autonavState};
g.h.show=function(){k4.prototype.show.call(this);g.lo(this.element,"ytp-show-tiles");g.X(this.player).g?g.zo(this.H):this.H.start();(this.D||this.C&&this.C!=this.O.clientPlaybackNonce)&&g.wK(this.player,!1);u4(this)?(w4(this),2==this.O.autonavState?g.O(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?p4(this.l,!0):m4(this.l):3==this.O.autonavState&&o4(this.l)):(g.wK(this.player,!0),w4(this))};
g.h.hide=function(){k4.prototype.hide.call(this);o4(this.l);w4(this)};
g.h.sL=function(a){g.hs(a)==this.element&&this.Lf()};
g.h.Lf=function(){if(this.u&&this.u.length){g.H(this.element,"ytp-endscreen-paginate");var a=g.EK(this.F,!0),b=g.AD(this.F);b&&(b=b.ec()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&z)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.pd(a.width/m||1,1,1.21);n*=g.pd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.I.element;g.Sh(a,m,n);g.Ah(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.u[0];c.u=f;j4(c,f,"hqdefault.jpg");g.I(this.element,"ytp-endscreen-takeover",u4(this));w4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.qd(q+this.A,l),0!=r){u=this.o[c];u||(u=new r4(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),F=Math.floor(n*(k+r)/e)-z-4,E=Math.floor(m*(f+r)/b)-C-4;g.Ih(u.element,C,z);g.Sh(u.element,E,F);g.Ah(u.element,"transitionDelay",(k+f)/20+"s");g.I(u.element,"ytp-videowall-still-mini",1==r);g.I(u.element,"ytp-videowall-still-large",2<r);r=u;q=this.u[q];r.o!=q&&(r.o=q,j4(r,q,g.jo(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),q=(q=q.Ub)&&q.itct)&&(u=r.l,g.X(u).F&&g.yO(u.app.T,r.element,q));c++}g.I(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.rf(e);this.o.length=c}};
g.h.IF=function(){var a=this.player.getVideoData();this.O!=a&&(this.A=0,this.u=v4(this,a),this.O=a,this.Lf())};
g.h.GF=function(){this.A+=this.o.length;this.Lf()};
g.h.HF=function(){this.A-=this.o.length;this.Lf()};
g.h.kE=function(){return!!this.l.o};
g.h.qr=function(a){1==a?(this.D=!1,this.C=this.O.clientPlaybackNonce,n4(this.l),this.Ga()&&this.Lf()):(this.D=!0,this.Ga()&&u4(this)&&(2==a?m4(this.l):3==a&&o4(this.l)))};
g.h.FF=function(a){if(a){for(a=0;a<this.o.length;a++)g.RK(this.F,this.o[a].element,!0);this.qr(1)}else this.C=null,this.D=!1;this.Lf()};
g.h.Pe=function(){return this.Ga()&&u4(this)};g.t(y4,g.aL);g.h=y4.prototype;g.h.Uk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!x4(this.player)||b;a=a.Nc||g.bz(a.Na);var c=g.WX(this.player.app);return b&&!a&&!c};
g.h.Pe=function(){return this.g.Pe()};
g.h.fE=function(){return this.Pe()?this.g.kE():!1};
g.h.U=function(){g.JK(this.player,"endscreen");g.aL.prototype.U.call(this)};
g.h.load=function(){g.aL.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.aL.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.VE=function(a){this.Uk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.WE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.bA=function(){g.JK(this.player,"endscreen");var a=this.player.getVideoData();a=new g.iE(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.B(this,a);var b=new g.iE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.B(this,b);g.GK(this.player,[a,b])};g.wV.endscreen=y4;})(_yt_player);
